version: '3'

services:
  postgres_card:
    build:
      context: .
      dockerfile: ../postgres/Dockerfile
    container_name: postgres_card
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    expose:
      - '5432'
    env_file:
      - ../postgres/.env
    networks:
      - card-network

networks:
  card-network:
    driver: bridge

volumes:
  postgres_data:
  static_files: